### ISSUE TITLE
Hosting is decomissioned/registration-walled?

### ISSUE THREAD

**Issue by bcdarwin** [CobraLab/MINC-VM#24]
I've never downloaded the minc-vm before but I referred it to a collaborator and she's confused since the .iso now asks for a Terraform Enterprise account ... is this expected?  There's also a 'decommisioned on may 18, 2018' banner, possibly related.

**Comment by gdevenyi** [comment]
Hosting was indeed decomissioned :(

Now available from the BIC servers.

Fixed by commit 0dbb7d43649dbe773ee1cc34eed362b0f90eb7c9

**Comment by gdevenyi** [comment]
Now VMs are not auto-built because I have to do it locally on my workstation and push it to the bic.

**Comment by bcdarwin** [comment]
Thanks!!
