### ISSUE TITLE
RMINC is not being installed

### ISSUE THREAD

**Issue by bcdarwin** [CobraLab/MINC-VM#25]
as it's not available via  https://cloud.r-project.org/ and so [this code](https://github.com/CobraLab/MINC-VM/blob/master/provision.sh#L202) fails silently.

**Comment by gdevenyi** [comment]
What's the right way to do this properly?

R is just an admin's nightmare at getting things properly installed.

**Comment by bcdarwin** [comment]
@cfhammill ?

**Comment by cfhammill** [comment]
`devtools::install_github("Mouse-Imaging-Centre/RMINC")`

**Comment by gdevenyi** [comment]
That will not install dependencies.

**Comment by cfhammill** [comment]
yes it will. For some reason `lmerTest` gets left behind, but I think that can be fixed with:

```
devtools::install_github("Mouse-Imaging-Centre/RMINC"
  , dependencies = c("Suggests", "Imports", "Depends", "LinkingTo"))
```

**Comment by gdevenyi** [comment]
Okay, so we're back to what I'm doing, that's equivalent to dependencies=TRUE.

It seems it doesn't accept the "repo =" option, even though the docs say that will be passed forward into the install command.

I'm now testing a version where I set the global R repo option instead.

**Comment by gdevenyi** [comment]
As a side question, how the heck do I force R to error on any failure, instead of continuing on in the script, making debugging incredibly difficult?

**Comment by bcdarwin** [comment]
I think using Rscript instead of R will work this way.

**Comment by hrallapalli-zz** [comment]
https://support.rstudio.com/hc/en-us/articles/200713843?version=1.0.153&mode=desktop#stopping-when-an-error-occurs

> options(error = browser())

Is this helpful?

**Comment by cfhammill** [comment]
RMINC has to come from github, it's not on CRAN. That's why that is failing. Dependencies = TRUE is the default as far as I know, you really need the "Suggests"

**Comment by cfhammill** [comment]
And yeah, don't use `R`, use `Rscript -e`, you're opening R in interactive mode which doesn't bubble errors to end the program.

**Comment by gdevenyi** [comment]
The original line of code is using install_url pointing to the release tarball on github.

I think the main issue here is that the R script always succeeds and never stops on error so I don't even know it went wrong.

I'll try Rscript -e

**Comment by gdevenyi** [comment]
Current failure mode:
```
    mincvm-virtualbox: Downloading package from url: https://github.com/Mouse-Imaging-Centre/RMINC/releases/download/v1.5.2.0/RMINC_1.5.2.0.tar.gz
    mincvm-virtualbox: Installation failed: error setting certificate verify locations:
    mincvm-virtualbox:   CAfile: microsoft-r-cacert.pem
    mincvm-virtualbox:   CApath: none
    mincvm-virtualbox: Downloading package from url: https://github.com/BIC-MNI/mni.cortical.statistics/archive/ver-0_9_5.tar.gz
    mincvm-virtualbox: Installation failed: error setting certificate verify locations:
    mincvm-virtualbox:   CAfile: microsoft-r-cacert.pem
    mincvm-virtualbox:   CApath: none

```

And Rscript happily continues on, and exits successfully. So, again I have a VM build without RMINC.

**Comment by cfhammill** [comment]
Well that's a pain, `devtools` doesn't throw an error when install fails (we're all learning together), so you need to wrap it:

```
r <- devtools::install_github(...)
if(!r) stop("RMINC installed failed, drat")
```

**Comment by bcdarwin** [comment]
Worth a bug report to `devtools`?

**Comment by cfhammill** [comment]
Ehhh, returning the success state of the install is valid. I wonder if it has a strictness argument...

**Comment by gdevenyi** [comment]
After much hackery, it finally works and builds again.

Still doesn't throw errors when R goes bad, even after wrapping things and upgrading warnings to errors. I'll just have to be very careful reading the logs.

**Comment by cfhammill** [comment]
https://github.com/CobraLab/MINC-VM/blob/master/provision.sh#L165

This isn't quite right I don't think. It doesn't throw a warning when it fails, it just returns `FALSE`. You need to translate that into an error:

```r
stopifnot(
  install_url("$RMINC", dependencies=TRUE, upgrade_dependencies=FALSE)
)
```

or if you want a more descriptive error

```r
r <- install_url("$RMINC", dependencies=TRUE, upgrade_dependencies=FALSE)
if(!r) stop("Failed to install RMINC")
```

**Comment by gdevenyi** [comment]
I based the wrapping on https://stackoverflow.com/a/26245048/4130016.

Maybe I should wrap that again with stopifnot as well?

**Comment by cfhammill** [comment]
that is for `install.packages` which does throw warnings, `devtools::install*` does not. Really all you need is the code I posted above, no handlers necessary.

That SO answer is bad for other reasons too, `tryCatch` solves the problem more cleanly.

**Comment by gdevenyi** [comment]
Am I doing something wrong?

```
cat <<-EOF | Rscript --vanilla -
r = getOption("repos") 
r["CRAN"] = 'http://cloud.r-project.org/'
options(repos = r)
rm(r)
library(devtools)
stopifnot((install_url("$RMINC", dependencies=TRUE, upgrade_dependencies=FALSE))
stopifnot((install_url("$mni_cortical_statistics", dependencies=TRUE, upgrade_dependencies=FALSE))
EOF
```

```
    mincvm-virtualbox: Error: unexpected symbol in:
    mincvm-virtualbox: "stopifnot((install_url("https://github.com/Mouse-Imaging-Centre/RMINC/releases/download/v1.5.2.0/RMINC_1.5.2.0.tar.gz", dependencies=TRUE, upgrade_dependencies=FALSE))
    mincvm-virtualbox: stopifnot"

```

**Comment by gdevenyi** [comment]
nevermind... unbalanced parenthesis...

**Comment by cfhammill** [comment]
that's usually the source of unexpected symbol, pleased it's working now :slightly_smiling_face:
