### ISSUE TITLE
$ANTSPATH is unset

### ISSUE THREAD

**Issue by dorkylever** [CobraLab/MINC-VM#34]
Hi Gabriel, 

antsRegistrationSyNQuick.sh requires $ANTSPATH to be set. Currently: 

(base) minc@mincvm:~$ echo $ANTSPATH

(base) minc@mincvm:~$ 

I'm unsure which directory ANTSPATH is meant to be set to...

Kind Regards,
Kyle Drover

**Comment by gdevenyi** [comment]
Technically this is an upstream bug with minc-toolkit-v2's packaging of ANTs. Of course most of our users don't ever touch the ANTs scripts.

Please open a bug there as well. In the meantime I'll fix it at the VM generation level.

You can fix by adding to ~/.bashrc, ''export ANTSPATH=/opt/minc/1.9.17/bin"

**Comment by dorkylever** [comment]
Yep the export fixed it, thanks Gabriel!!
 
I've opened the bug in minc-toolkit-v2:
https://github.com/BIC-MNI/minc-toolkit-v2/issues/93

Kind Regards, 
Kyle Drover

**Comment by vfonov** [comment]
it was fixed in 1.9.18: https://github.com/BIC-MNI/minc-toolkit-v2/blob/develop-1.9.18/minc-toolkit-config.unix.sh.cmake#L13 
https://github.com/BIC-MNI/minc-toolkit-v2/commit/449ef1af17a33cf888ae2973101b93ae29d60b1b

**Comment by gdevenyi** [comment]
Cheers thanks @vfonov
