### ISSUE TITLE
Error when opening MINC files using display

### ISSUE THREAD

**Issue by rwickens** [CobraLab/MINC-VM#36]
Hi there, I get the following error (see screen shot) when I open .mnc files using display. What would you recommend to get around this? Best regards, Rebekah 

![73375528_2500938550228951_1041670495746916352_n](https://user-images.githubusercontent.com/24905802/69886912-6834f080-12b2-11ea-9828-4cfb3102b166.png)

**Comment by gdevenyi** [comment]
the command for opening minc files is "Display" not "display" :)

**Comment by rwickens** [comment]
No kidding. It works. Thank you, @gdevenyi !
