### ISSUE TITLE
Copy paste 

### ISSUE THREAD

**Issue by rwickens** [CobraLab/MINC-VM#38]
Hi there, downloaded your newest release. 
Copy-pasting between my host machine and the VM isn't working, even though I've enabled bidirectional shared clipboards. Any thoughts on what I might be missing? Didn't have this issue with the previous VM. Thanks!

**Comment by gdevenyi** [comment]
virtualbox has been terrible at properly updating their guest additions to actually support clipboard. I haven't had it working in a long time. Not anything MINC-VM can do to fix it either.

**Comment by gdevenyi** [comment]
Today's uploaded version has working copy-paste.
