### ISSUE TITLE
VBox guest addition 6.1.4 bug

### ISSUE THREAD

**Issue by EtienneAumont** [CobraLab/MINC-VM#39]
Shared clipboard doesn't work in the last version of the VM. There is a known issue where guest additions 6.1.4 have a faulty shared clipboard. I tried updating to 6.1.12, but the whole VM simply broke down. Therefore I'd recommend not installing the latest (March 2020) version and opt for an older build.
Edit: I just realized that older build were not available on the download link. May I please have access to the previous version?

**Comment by gdevenyi** [comment]
I have built and am currently uploading a 6.1.12 version, I have tested clipboard and it works.
