### ISSUE TITLE
Minc commands issue

### ISSUE THREAD

**Issue by EtienneAumont** [CobraLab/MINC-VM#40]
Hi there,

I'm having an issue when using mincstats and mincmath on the newest VM version. 
Whenever a .mnc file is entered, I get this error message, no matter the .mnc file I use:
ncopen: filename "t-test_AD6-6_agecor.mnc": Not a netCDF file
miopen: MINC package entry point

Yet they can be read on register and Display.

Is there anything I have to install to fix this?

**Comment by gdevenyi** [comment]
Please share an example file

**Comment by EtienneAumont** [comment]
Any file will do the same, here is one of the MNI templates
![image](https://user-images.githubusercontent.com/57918213/89220451-95534480-d59f-11ea-8f4b-ed966250b407.png)

File used is here: https://www.dropbox.com/s/ok8u3jmucz8jm6v/mni_icbm152_t1_tal_nlin_sym_09c.mnc?dl=0

Thanks

**Comment by EtienneAumont** [comment]
And yet register reads it without problem
![image](https://user-images.githubusercontent.com/57918213/89220856-4bb72980-d5a0-11ea-9cec-2ee0abb9fe0b.png)

**Comment by gdevenyi** [comment]
The mincmath command needs an output file no?

**Comment by EtienneAumont** [comment]
Yes, the last argument (test.mnc) is the output.

**Comment by gdevenyi** [comment]
I am unable to reproduce your report on a fresh copy of the VM within a lxterm just opened:
![image](https://user-images.githubusercontent.com/3001850/89237279-c728d300-d5c0-11ea-8301-7bfca48ea02c.png)

**Comment by EtienneAumont** [comment]
Thank you for verifying. A fresh install does seem to be working.

**Comment by gdevenyi** [comment]
Glad its working.
