### ISSUE TITLE
internet application

### ISSUE THREAD

**Issue by mirpie** [CobraLab/MINC-VM#41]
I have some R files that I need to access from the VM that are stored in OneDrive. However, when I click on the internet browser icon it returns an error. Is there any way to access the internet or add a valid browser?

Thanks in advance!

**Comment by gdevenyi** [comment]
No browser is installed.

You have full access to apt-get. Install whatever you want, or use the shared folders as documented in the README, https://github.com/CoBrALab/MINC-VM#usage-instructions
